### ISSUE TITLE
You need to click login twice to actually login 

### ISSUE THREAD

**Issue by marisid** [Authosaurus/velocity-tracker#36]
Once to redirect to Github and once more to actually get to the user page.

**Comment by marisid** [comment]
Actually it's a bug that we all have I think. Follow Nick's suggestions to make it go away :smile:

**Comment by tbtommyb** [comment]
This appears to be due to Chrome's handling of cookies (see discussion [here](https://github.com/hapijs/yar/issues/101)). Hapi has an 'isSameSite' flag for config but it isn't accessible in the options for hapi-auth-cookie (see PR [here](https://github.com/hapijs/hapi-auth-cookie/pull/142)).

I *think* the PR above should fix this by adding the config when creating the server. I have tried to test it but it's difficult to be sure that a particular request wasn't going to work anyway without the change.
